version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000

  gateway:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '3080:80'
